#!/bin/sh
set -e -x

cd /resources

# Installing temporary tools
apk add --no-cache curl

# Downloading grafana
curl -SL \
  -o /resources/grafana.tar.gz  \
  https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-${GRAFANA_VERSION}.linux-x64.tar.gz

# Installing grafana dependencies
apk add --no-cache \
  ca-certificates=${CACERTIFICATES_VERSION}

# Installing grafana
tar -zxvf /resources/grafana.tar.gz

mkdir -p /opt/grafana

mv /resources/grafana-${GRAFANA_VERSION}/conf   /opt/grafana
mv /resources/grafana-${GRAFANA_VERSION}/bin    /opt/grafana
mv /resources/grafana-${GRAFANA_VERSION}/public /opt/grafana

rm /opt/grafana/conf/ldap.toml /opt/grafana/conf/sample.ini
rm /opt/grafana/bin/*.md5

adduser \
  -h /opt/grafana \
  -s /bin/sh \
  -D \
  -H \
  grafana \
  grafana

chown -R grafana:grafana /opt/grafana

ln -s /opt/grafana/bin/grafana-server /usr/sbin/grafana-server
ln -s /opt/grafana/bin/grafana-cli /usr/sbin/grafana-cli

# Adding a link from musl to glibc since so are compatible
# https://stackoverflow.com/questions/34729748/installed-go-binary-not-found-in-path-on-alpine-linux-docker
mkdir /lib64
ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

apk del --purge \
  curl
